version: "3.8"

services:      
  piece-db:
    image: mariadb:11
    container_name: piece-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
    - msa-network

networks:
  msa-network:
    external: true # 이미 만들어진 인프라 네트워크를 사용함